// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dihbjitqpegziafkdaxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpaGJqaXRxcGVnemlhZmtkYXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzUwNDQsImV4cCI6MjA2ODI1MTA0NH0.RuajP6eH7wHwBq96NBf53g33Tm9IUr1-PF3U8B6lK60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});